port: ":8084"

database:
  host: "localhost"
  port: 5432
  user: "behouba"
  password: "mana"
  dbName: "akwaba_express_dev"

secretKey: "$GPzMX9x~jn5R#,A"

mapApiKey: "AIzaSyC3yF2GOndSJqklHFWyMoEIHus91xFYjaI"