port: ":8080"

database:
  host: "localhost"
  port: 5432
  user: "behouba"
  password: "mana"
  dbName: "akwaba_express"

mail:
  smtp: "mail.spamora.net"
  email: "notifications@akwabaexpress.ci"
  password: "akwabaexpress"
  port: 587

mapApiKey: "AIzaSyC3yF2GOndSJqklHFWyMoEIHus91xFYjaI"